#!/bin/bash

if [[ -f env/bin/activate ]]; then
    . env/bin/activate
else
    virtualenv --system-site-packages env
    . env/bin/activate
    easy_install -U pip
fi

if [[ ! "$INI_FILE" ]]; then
    INI_FILE="production.ini";
fi

cd src
python setup.py develop
make INI_FILE="$INI_FILE"
uwsgi --ini "$INI_FILE"
