#!/bin/bash

if [[ ! -f env/bin/activate ]]; then
    virtualenv --system-site-packages env
fi

. env/bin/activate

if [[ ! "$INI_FILE" ]]; then
    INI_FILE="production.ini";
fi

cd src
python setup.py develop
make INI_FILE="$INI_FILE"
uwsgi --ini "$INI_FILE"
