#!/bin/sh

IP_ADDRESS="$(ip addr show eth0 | grep 'inet ' | awk '{ print $2 }' | cut -d '/' -f1)"

if [ ! "$DATABASE" ]; then
    DATABASE="db"
fi

password=${MASTER_PASSWORD:-$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)}

psql -c "ALTER USER postgres WITH PASSWORD '$password';"
psql -c "CREATE DATABASE $DATABASE;"

echo "* Credentials: url=\"postgresql://postgres:${password}@${IP_ADDRESS}/$DATABASE\""
